GAME_SOUND_EFFECT_EVENT	= 100
GAME_SOUND_MUSIC_EVENT	= 200
GAME_SOUND_MENU_EVENT	= 300



#EFFECTS
GAME_SOUND_EFFECT_EVENT_AMBIENTEAGUASPLASHS = 1
GAME_SOUND_EFFECT_EVENT_AMBIENTEANDARARENACORTO = 2
GAME_SOUND_EFFECT_EVENT_AMBIENTEANDARRAMAS = 3
GAME_SOUND_EFFECT_EVENT_AMBIENTEBOSQUECORTO = 4
GAME_SOUND_EFFECT_EVENT_AMBIENTECASCADA1 =	5
GAME_SOUND_EFFECT_EVENT_AMBIENTECASCADA2 = 6
GAME_SOUND_EFFECT_EVENT_AMBIENTECASCOTESCAIDA = 7
GAME_SOUND_EFFECT_EVENT_AMBIENTECOLISEO = 8
GAME_SOUND_EFFECT_EVENT_AMBIENTEFUEGO1 = 9
GAME_SOUND_EFFECT_EVENT_AMBIENTEFUEGO2 = 10
GAME_SOUND_EFFECT_EVENT_AMBIENTEFUEGONOLOOP = 11
GAME_SOUND_EFFECT_EVENT_AMBIENTEGENTEPANICO = 12
GAME_SOUND_EFFECT_EVENT_AMBIENTEGENTEPANICOCORTO = 13
GAME_SOUND_EFFECT_EVENT_AMBIENTEGENTESUSURROS = 14
GAME_SOUND_EFFECT_EVENT_AMBIENTEGRANJA = 15
GAME_SOUND_EFFECT_EVENT_AMBIENTEHOJASMANIPULAR = 16
GAME_SOUND_EFFECT_EVENT_AMBIENTELLUVIA = 17
GAME_SOUND_EFFECT_EVENT_AMBIENTENOCHE = 18
GAME_SOUND_EFFECT_EVENT_AMBIENTEPISARTIERRA = 19
GAME_SOUND_EFFECT_EVENT_AMBIENTERATA1 = 20
GAME_SOUND_EFFECT_EVENT_AMBIENTERATA2 = 21
GAME_SOUND_EFFECT_EVENT_AMBIENTERATA3 = 22
GAME_SOUND_EFFECT_EVENT_AMBIENTERATA4 = 23
GAME_SOUND_EFFECT_EVENT_AMBIENTERIO1 = 24
GAME_SOUND_EFFECT_EVENT_AMBIENTERIO2 = 25
GAME_SOUND_EFFECT_EVENT_AMBIENTEVIENTO = 26

#armas
GAME_SOUND_EFFECT_EVENT_ARMADAGAIMPACTO = 27
GAME_SOUND_EFFECT_EVENT_ARMAESPADAATAQUE1 =	28
GAME_SOUND_EFFECT_EVENT_ARMAESPADAATAQUE2 =	29	
GAME_SOUND_EFFECT_EVENT_ARMAESPADAEQUIPAR =	30
GAME_SOUND_EFFECT_EVENT_ARMAESPADAIMPACTO =	31
GAME_SOUND_EFFECT_EVENT_ARMAFLECHAATAQUE1 =	32
GAME_SOUND_EFFECT_EVENT_ARMAFLECHAATAQUE2 =	33
GAME_SOUND_EFFECT_EVENT_ARMAFLECHAIMPACTO1 = 34
GAME_SOUND_EFFECT_EVENT_ARMAFLECHAIMPACTO2 = 35
GAME_SOUND_EFFECT_EVENT_ARMAHORCAATAQUE = 36
GAME_SOUND_EFFECT_EVENT_ARMAHORCAIMPACTO = 37
GAME_SOUND_EFFECT_EVENT_ARMAHORCAIMPACTO2 = 38
GAME_SOUND_EFFECT_EVENT_ARMAMAGIAATAQUE = 39
GAME_SOUND_EFFECT_EVENT_ARMAMANOTAZOIMPACTO	 = 40
GAME_SOUND_EFFECT_EVENT_ARMAPUNHOIMPACTO = 41

#personajes
GAME_SOUND_EFFECT_EVENT_PERSONAJEGRITOSTANDARD = 42
GAME_SOUND_EFFECT_EVENT_PERSONAJEVIDABAJA = 43
GAME_SOUND_EFFECT_EVENT_PERSONAJESGRITOHOMBRE = 44

GAME_SOUND_EFFECT_EVENT_STOP = 45
GAME_SOUND_EFFECT_EVENT_PAUSE = 46
GAME_SOUND_EFFECT_EVENT_RESUME = 47





#MUSIC
GAME_SOUND_MUSIC_EVENT_MUSIC_1 = 101
GAME_SOUND_MUSIC_EVENT_MUSIC_2 = 102
GAME_SOUND_MUSIC_EVENT_MUSIC_3 = 103
GAME_SOUND_MUSIC_EVENT_MUSIC_4 = 104
GAME_SOUND_MUSIC_EVENT_MUSIC_5 = 105
GAME_SOUND_MUSIC_EVENT_MUSIC_6 = 106
GAME_SOUND_MUSIC_EVENT_MUSIC_STOP = 107
GAME_SOUND_MUSIC_EVENT_MUSIC_PAUSE = 108
GAME_SOUND_MUSIC_EVENT_MUSIC_RESUME = 109






#MENU
GAME_SOUND_MENU = 201
GAME_SOUND_MENU_EVENT_MOVE_UP = 202
GAME_SOUND_MENU_EVENT_MOVE_DOWN = 203
GAME_SOUND_MENU_EVENT_MOVE_LEFT = 204
GAME_SOUND_MENU_EVENT_MOVE_RIGHT = 205
GAME_SOUND_MENU_EVENT_OK = 206
GAME_SOUND_MENU_EVENT_CANCEL = 207
GAME_SOUND_MENU_EVENT_EXIT = 208
